# 기본세팅

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
sns.set(font='Malgun Gothic',
        rc={'axes.unicode_minus':False},
        style='darkgrid')

In [3]:
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('retina')

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\2106068084.py:2: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats('retina')

# 데이터 불러오기

In [24]:
rank=pd.read_csv('체육생활이용정보.csv',encoding='cp949')
rank

,기준년월,기준년도,기준월,시도코드,시도명,시군구코드,시군구명,시군구별인구수,메인수요시설구분명,메인수요시설명,시군구별시설수,인당시설수,인당시설순위수
0,202008,2020,8,1100000000,서울특별시,1111000000,종로구,149962,자주이용하는 공공시설 1순위,간이운동장,28,0.00019,132
1,202008,2020,8,1100000000,서울특별시,1111000000,종로구,149962,자주이용하는 민간시설 1순위,체력단련장,47,0.00031,6
2,202008,2020,8,1100000000,서울특별시,1111000000,종로구,149962,자주이용하는 공공시설 2순위,체력단련장,3,0.00002,66
3,202008,2020,8,1100000000,서울특별시,1111000000,종로구,149962,자주이용하는 민간시설 2순위,골프장/골프연습장,25,0.00017,123
4,202008,2020,8,1100000000,서울특별시,1111000000,종로구,149962,자주이용하는 공공시설 3순위,수영장,3,0.00002,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48285,202204,2022,4,5000000000,제주특별자치도,5013000000,서귀포시,184337,자주이용하는 민간시설 3순위,수영장,18,0.00010,3
48286,202204,2022,4,5000000000,제주특별자치도,5011000000,제주시,493076,자주이용하는 공공시설 5순위,테니스장,4,0.00001,160
48287,202204,2022,4,5000000000,제주특별자치도,5013000000,서귀포시,184337,자주이용하는 민간시설 4순위,당구장,52,0.00028,122
48288,202204,2022,4,5000000000,제주특별자치도,5013000000,서귀포시,184337,자주이용하는 공공시설 5순위,테니스장,4,0.00002,95
48289,202204,2022,4,5000000000,제주특별자치도,5013000000,서귀포시,184337,자주이용하는 민간시설 5순위,체육도장,32,0.00017,178

# 데이터 전처리

In [25]:
rank=rank[['기준년도','기준월','시도명','시군구명','시군구별인구수','메인수요시설구분명','메인수요시설명','시군구별시설수']]
rank

       기준년도  기준월      시도명  시군구명  시군구별인구수        메인수요시설구분명    메인수요시설명  시군구별시설수
0      2020    8    서울특별시   종로구   149962  자주이용하는 공공시설 1순위      간이운동장       28
1      2020    8    서울특별시   종로구   149962  자주이용하는 민간시설 1순위      체력단련장       47
2      2020    8    서울특별시   종로구   149962  자주이용하는 공공시설 2순위      체력단련장        3
3      2020    8    서울특별시   종로구   149962  자주이용하는 민간시설 2순위  골프장/골프연습장       25
4      2020    8    서울특별시   종로구   149962  자주이용하는 공공시설 3순위        수영장        3
...     ...  ...      ...   ...      ...              ...        ...      ...
48285  2022    4  제주특별자치도  서귀포시   184337  자주이용하는 민간시설 3순위        수영장       18
48286  2022    4  제주특별자치도   제주시   493076  자주이용하는 공공시설 5순위       테니스장        4
48287  2022    4  제주특별자치도  서귀포시   184337  자주이용하는 민간시설 4순위        당구장       52
48288  2022    4  제주특별자치도  서귀포시   184337  자주이용하는 공공시설 5순위       테니스장        4
48289  2022    4  제주특별자치도  서귀포시   184337  자주이용하는 민간시설 5순위       체육도장       32

[48290 rows x 8 columns]

In [29]:
rank_vs=rank.groupby(['기준년도','시도명','메인수요시설구분명','메인수요시설명'])['시군구별시설수'].mean()
rank_vs=rank_vs.to_frame()
rank_vs=rank_vs.reset_index()
rank_vs

     기준년도   시도명        메인수요시설구분명    메인수요시설명    시군구별시설수
0    2020   강원도  자주이용하는 공공시설 1순위      간이운동장  66.000000
1    2020   강원도  자주이용하는 공공시설 2순위      체력단련장   1.555556
2    2020   강원도  자주이용하는 공공시설 3순위        수영장   0.722222
3    2020   강원도  자주이용하는 공공시설 4순위        축구장   4.222222
4    2020   강원도  자주이용하는 공공시설 5순위       테니스장   3.888889
..    ...   ...              ...        ...        ...
505  2022  충청북도  자주이용하는 민간시설 1순위      체력단련장  28.886364
506  2022  충청북도  자주이용하는 민간시설 2순위  골프장/골프연습장  36.977273
507  2022  충청북도  자주이용하는 민간시설 3순위        수영장   1.818182
508  2022  충청북도  자주이용하는 민간시설 4순위        당구장  53.318182
509  2022  충청북도  자주이용하는 민간시설 5순위       체육도장  37.045455

[510 rows x 5 columns]

In [31]:
rank_vs[(rank_vs['시도명']=='서울특별시')&(rank_vs['기준년도']==2021)]

     기준년도    시도명        메인수요시설구분명    메인수요시설명     시군구별시설수
250  2021  서울특별시  자주이용하는 공공시설 1순위      간이운동장   37.683333
251  2021  서울특별시  자주이용하는 공공시설 2순위      체력단련장    3.310000
252  2021  서울특별시  자주이용하는 공공시설 3순위        수영장    2.403333
253  2021  서울특별시  자주이용하는 공공시설 4순위        축구장    1.793333
254  2021  서울특별시  자주이용하는 공공시설 5순위       테니스장    1.746667
255  2021  서울특별시  자주이용하는 민간시설 1순위      체력단련장   96.853333
256  2021  서울특별시  자주이용하는 민간시설 2순위  골프장/골프연습장   78.056667
257  2021  서울특별시  자주이용하는 민간시설 3순위        수영장    4.870000
258  2021  서울특별시  자주이용하는 민간시설 4순위        당구장  137.460000
259  2021  서울특별시  자주이용하는 민간시설 5순위       체육도장   92.536667

In [32]:
2021년 서울의 평균 간이운동장 개수(942개)가 2021년 서울의 체력상태(59.56%)랑 관련있을까?

Object `관련있을까` not found.

In [36]:
rank_vs_pg=rank_vs[(rank_vs['메인수요시설명']=='간이운동장')&(rank_vs['시도명']=='서울특별시')]
rank_vs_pg

     기준년도    시도명        메인수요시설구분명 메인수요시설명    시군구별시설수
80   2020  서울특별시  자주이용하는 공공시설 1순위   간이운동장  37.080000
250  2021  서울특별시  자주이용하는 공공시설 1순위   간이운동장  37.683333
420  2022  서울특별시  자주이용하는 공공시설 1순위   간이운동장  38.480000

In [39]:
rank_re = rank.copy()
rank_re

       기준년도  기준월      시도명  시군구명  시군구별인구수        메인수요시설구분명    메인수요시설명  시군구별시설수
0      2020    8    서울특별시   종로구   149962  자주이용하는 공공시설 1순위      간이운동장       28
1      2020    8    서울특별시   종로구   149962  자주이용하는 민간시설 1순위      체력단련장       47
2      2020    8    서울특별시   종로구   149962  자주이용하는 공공시설 2순위      체력단련장        3
3      2020    8    서울특별시   종로구   149962  자주이용하는 민간시설 2순위  골프장/골프연습장       25
4      2020    8    서울특별시   종로구   149962  자주이용하는 공공시설 3순위        수영장        3
...     ...  ...      ...   ...      ...              ...        ...      ...
48285  2022    4  제주특별자치도  서귀포시   184337  자주이용하는 민간시설 3순위        수영장       18
48286  2022    4  제주특별자치도   제주시   493076  자주이용하는 공공시설 5순위       테니스장        4
48287  2022    4  제주특별자치도  서귀포시   184337  자주이용하는 민간시설 4순위        당구장       52
48288  2022    4  제주특별자치도  서귀포시   184337  자주이용하는 공공시설 5순위       테니스장        4
48289  2022    4  제주특별자치도  서귀포시   184337  자주이용하는 민간시설 5순위       체육도장       32

[48290 rows x 8 columns]

In [55]:
rank_re = rank_re[['기준년도','메인수요시설명','시군구별시설수']]
rank_re = rank_re.groupby(['기준년도','메인수요시설명']).시군구별시설수.sum().reset_index()

rank_re.loc[(rank_re['기준년도'] == 2020) & (rank_re['메인수요시설명'] == '간이운동장'),'시군구별시설수'] = 70520 / (70520+50660+93710+5050+47015+69430+4430+3335)
rank_re.loc[(rank_re['기준년도'] == 2020) & (rank_re['메인수요시설명'] == '골프장/골프연습장'),'시군구별시설수'] = 50660 / (70520+50660+93710+5050+47015+69430+4430+3335)
rank_re.loc[(rank_re['기준년도'] == 2020) & (rank_re['메인수요시설명'] == '당구장'),'시군구별시설수'] = 93710 / (70520+50660+93710+5050+47015+69430+4430+3335)
rank_re.loc[(rank_re['기준년도'] == 2020) & (rank_re['메인수요시설명'] == '수영장'),'시군구별시설수'] = 5050 / (70520+50660+93710+5050+47015+69430+4430+3335)
rank_re.loc[(rank_re['기준년도'] == 2020) & (rank_re['메인수요시설명'] == '체력단련장'),'시군구별시설수'] = 47015 / (70520+50660+93710+5050+47015+69430+4430+3335)
rank_re.loc[(rank_re['기준년도'] == 2020) & (rank_re['메인수요시설명'] == '체육도장'),'시군구별시설수'] = 69430 / (70520+50660+93710+5050+47015+69430+4430+3335)
rank_re.loc[(rank_re['기준년도'] == 2020) & (rank_re['메인수요시설명'] == '축구장'),'시군구별시설수'] = 4430 / (70520+50660+93710+5050+47015+69430+4430+3335)
rank_re.loc[(rank_re['기준년도'] == 2020) & (rank_re['메인수요시설명'] == '테니스장'),'시군구별시설수'] = 3335 / (70520+50660+93710+5050+47015+69430+4430+3335)

rank_re.loc[(rank_re['기준년도'] == 2021) & (rank_re['메인수요시설명'] == '간이운동장'),'시군구별시설수'] = 195767 / (195767+126655+211156+12733+121377+165824+10000+8240)
rank_re.loc[(rank_re['기준년도'] == 2021) & (rank_re['메인수요시설명'] == '골프장/골프연습장'),'시군구별시설수'] = 126655 / (195767+126655+211156+12733+121377+165824+10000+8240)
rank_re.loc[(rank_re['기준년도'] == 2021) & (rank_re['메인수요시설명'] == '당구장'),'시군구별시설수'] = 211156 / (195767+126655+211156+12733+121377+165824+10000+8240)
rank_re.loc[(rank_re['기준년도'] == 2021) & (rank_re['메인수요시설명'] == '수영장'),'시군구별시설수'] = 12733 / (195767+126655+211156+12733+121377+165824+10000+8240)
rank_re.loc[(rank_re['기준년도'] == 2021) & (rank_re['메인수요시설명'] == '체력단련장'),'시군구별시설수'] = 121377 / (195767+126655+211156+12733+121377+165824+10000+8240)
rank_re.loc[(rank_re['기준년도'] == 2021) & (rank_re['메인수요시설명'] == '체육도장'),'시군구별시설수'] = 165824 / (195767+126655+211156+12733+121377+165824+10000+8240)
rank_re.loc[(rank_re['기준년도'] == 2021) & (rank_re['메인수요시설명'] == '축구장'),'시군구별시설수'] = 10000 / (195767+126655+211156+12733+121377+165824+10000+8240)
rank_re.loc[(rank_re['기준년도'] == 2021) & (rank_re['메인수요시설명'] == '테니스장'),'시군구별시설수'] = 8240 / (195767+126655+211156+12733+121377+165824+10000+8240)

rank_re.loc[(rank_re['기준년도'] == 2022) & (rank_re['메인수요시설명'] == '간이운동장'),'시군구별시설수'] = 75697 / (75697+45893+66552+4484+45277+55726+3893+2857)
rank_re.loc[(rank_re['기준년도'] == 2022) & (rank_re['메인수요시설명'] == '골프장/골프연습장'),'시군구별시설수'] = 45893 / (75697+45893+66552+4484+45277+55726+3893+2857)
rank_re.loc[(rank_re['기준년도'] == 2022) & (rank_re['메인수요시설명'] == '당구장'),'시군구별시설수'] = 66552 / (75697+45893+66552+4484+45277+55726+3893+2857)
rank_re.loc[(rank_re['기준년도'] == 2022) & (rank_re['메인수요시설명'] == '수영장'),'시군구별시설수'] = 4484 / (75697+45893+66552+4484+45277+55726+3893+2857)
rank_re.loc[(rank_re['기준년도'] == 2022) & (rank_re['메인수요시설명'] == '체력단련장'),'시군구별시설수'] = 45277 / (75697+45893+66552+4484+45277+55726+3893+2857)
rank_re.loc[(rank_re['기준년도'] == 2022) & (rank_re['메인수요시설명'] == '체육도장'),'시군구별시설수'] = 55726 / (75697+45893+66552+4484+45277+55726+3893+2857)
rank_re.loc[(rank_re['기준년도'] == 2022) & (rank_re['메인수요시설명'] == '축구장'),'시군구별시설수'] = 3893 / (75697+45893+66552+4484+45277+55726+3893+2857)
rank_re.loc[(rank_re['기준년도'] == 2022) & (rank_re['메인수요시설명'] == '테니스장'),'시군구별시설수'] = 2857 / (75697+45893+66552+4484+45277+55726+3893+2857)

rank_re

    기준년도    메인수요시설명   시군구별시설수
0   2020      간이운동장  0.204911
1   2020  골프장/골프연습장  0.147203
2   2020        당구장  0.272294
3   2020        수영장  0.014674
4   2020      체력단련장  0.136612
5   2020       체육도장  0.201743
6   2020        축구장  0.012872
7   2020       테니스장  0.009691
8   2021      간이운동장  0.229840
9   2021  골프장/골프연습장  0.148699
10  2021        당구장  0.247908
11  2021        수영장  0.014949
12  2021      체력단련장  0.142503
13  2021       체육도장  0.194686
14  2021        축구장  0.011741
15  2021       테니스장  0.009674
16  2022      간이운동장  0.252005
17  2022  골프장/골프연습장  0.152784
18  2022        당구장  0.221560
19  2022        수영장  0.014928
20  2022      체력단련장  0.150733
21  2022       체육도장  0.185519
22  2022        축구장  0.012960
23  2022       테니스장  0.009511

In [71]:
yearlist = rank_re['기준년도'].unique().tolist()
rank_re_an = rank_re[rank_re['기준년도'] == 2020][['메인수요시설명','시군구별시설수']].copy()
rank_re_an = rank_re_an.set_index('메인수요시설명')
rank_re_an.columns = [2020]

for index in yearlist[1:]:
    add_rank = rank_re[rank_re['기준년도']==index][['메인수요시설명','시군구별시설수']].copy()
    add_rank = add_rank.set_index('메인수요시설명')
    add_rank.columns = [index]
    rank_re_an = pd.concat([rank_re_an,add_rank], axis=1)
    
rank_re_an = rank_re_an.transpose().reset_index()
rank_re_an.columns = ['연도','간이운동장','골프장/골프연습장','당구장','수영장','체력단련장','체육도장','축구장','테니스장']
rank_re_an

,연도,간이운동장,골프장/골프연습장,당구장,수영장,체력단련장,체육도장,축구장,테니스장
0,2020,0.204911,0.147203,0.272294,0.014674,0.136612,0.201743,0.012872,0.009691
1,2021,0.229840,0.148699,0.247908,0.014949,0.142503,0.194686,0.011741,0.009674
2,2022,0.252005,0.152784,0.221560,0.014928,0.150733,0.185519,0.012960,0.009511

In [63]:
df=pd.read_csv('지역별 체력통계.csv',encoding='cp949')
df['시군구']=df['센터 시군구명'].str.split(expand=True)[0]
df2=df[['센터 시도명','시군구','측정년도','측정횟수','유소년 회원 수','청소년 회원 수','성인 회원 수','노인 회원 수','남성 회원수','여성 회원수','금상 수상 건수','은상 수상 건수','동상 수상 건수','참가상 수상 건수']]
df2['센터 시도명']=df2['센터 시도명'].replace('경기','경기도')
df2['센터 시도명']=df2['센터 시도명'].replace('서울','서울특별시')
df2['센터 시도명']=df2['센터 시도명'].replace('충북','충청북도')
df2['센터 시도명']=df2['센터 시도명'].replace('부산','부산광역시')
df2['센터 시도명']=df2['센터 시도명'].replace('전남','전라남도')
df2['센터 시도명']=df2['센터 시도명'].replace('경북','경상북도')
df2['센터 시도명']=df2['센터 시도명'].replace('강원','강원도')
df2['센터 시도명']=df2['센터 시도명'].replace('광주','광주광역시')
df2['센터 시도명']=df2['센터 시도명'].replace('전북','전라북도')
df2['센터 시도명']=df2['센터 시도명'].replace('경남','경상남도')
df2['센터 시도명']=df2['센터 시도명'].replace('인천','인천광역시')
df2['센터 시도명']=df2['센터 시도명'].replace('대전','대전광역시')
df2['센터 시도명']=df2['센터 시도명'].replace('충남','충청남도')
df2['센터 시도명']=df2['센터 시도명'].replace('대구','대구광역시')
df2['센터 시도명']=df2['센터 시도명'].replace('제주','제주특별자치도')
df2['센터 시도명']=df2['센터 시도명'].replace('세종','세종특별자치시')
df2['센터 시도명']=df2['센터 시도명'].replace('울산','울산광역시')
df2 = df2[['측정년도','금상 수상 건수','은상 수상 건수','동상 수상 건수','참가상 수상 건수']]
df2 = df2.loc[df2.측정년도 >=2020].groupby('측정년도').sum().reset_index()

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('경기','경기도')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('서울','서울특별시')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('충북','충청북도')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('부산','부산광역시')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('전남','전라남도')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('경북','경상북도')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('강원','강원도')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('광주','광주광역시')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('전북','전라북도')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('경남','경상남도')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('인천','인천광역시')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('대전','대전광역시')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('충남','충청남도')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('대구','대구광역시')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('제주','제주특별자치도')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('세종','세종특별자치시')
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21824\4271776327.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['센터 시도명']=df2['센터 시도명'].replace('울산','울산광역시')

In [72]:
df2_ratio = df2.copy()
df2_ratio.columns = ['연도','금상','은상','동상','참가상']
df2_ratio['금상'] = df2['금상 수상 건수'] / (df2['금상 수상 건수']+df2['은상 수상 건수']+df2['동상 수상 건수']+df2['참가상 수상 건수'])
df2_ratio['은상'] = df2['은상 수상 건수'] / (df2['금상 수상 건수']+df2['은상 수상 건수']+df2['동상 수상 건수']+df2['참가상 수상 건수'])
df2_ratio['동상'] = df2['동상 수상 건수'] / (df2['금상 수상 건수']+df2['은상 수상 건수']+df2['동상 수상 건수']+df2['참가상 수상 건수'])
df2_ratio['참가상'] = df2['참가상 수상 건수'] / (df2['금상 수상 건수']+df2['은상 수상 건수']+df2['동상 수상 건수']+df2['참가상 수상 건수'])
df2_ratio

     연도        금상        은상        동상       참가상
0  2020  0.070290  0.122190  0.208010  0.599510
1  2021  0.055287  0.138852  0.207130  0.598731
2  2022  0.057332  0.145428  0.212155  0.585084

In [73]:
rank_health = pd.merge(rank_re_an,df2_ratio)
rank_health

,연도,간이운동장,골프장/골프연습장,당구장,수영장,체력단련장,체육도장,축구장,테니스장,금상,은상,동상,참가상
0,2020,0.204911,0.147203,0.272294,0.014674,0.136612,0.201743,0.012872,0.009691,0.070290,0.122190,0.208010,0.599510
1,2021,0.229840,0.148699,0.247908,0.014949,0.142503,0.194686,0.011741,0.009674,0.055287,0.138852,0.207130,0.598731
2,2022,0.252005,0.152784,0.221560,0.014928,0.150733,0.185519,0.012960,0.009511,0.057332,0.145428,0.212155,0.585084

In [74]:
rank_health.corr()

,연도,간이운동장,골프장/골프연습장,당구장,수영장,체력단련장,체육도장,축구장,테니스장,금상,은상,동상,참가상
연도,1.000000,0.999426,0.965969,-0.999751,0.829021,0.995457,-0.997195,0.064680,-0.904355,-0.796309,0.970014,0.772334,-0.889017
간이운동장,0.999426,1.000000,0.956652,-0.998421,0.847491,0.991660,-0.994087,0.030834,-0.889376,-0.816345,0.977691,0.750369,-0.872994
골프장/골프연습장,0.965969,0.956652,1.000000,-0.971501,0.656163,0.986208,-0.982619,0.320594,-0.983969,-0.612751,0.874137,0.910354,-0.977195
당구장,-0.999751,-0.998421,-0.971501,1.000000,-0.816335,-0.997334,0.998617,-0.086934,0.913654,0.782611,-0.964348,-0.786317,0.899013
수영장,0.829021,0.847491,0.656163,-0.816335,1.000000,0.772010,-0.784841,-0.504425,-0.511066,-0.998422,0.940079,0.285056,-0.480962
체력단련장,0.995457,0.991660,0.986208,-0.997334,0.772010,1.000000,-0.999791,0.159399,-0.940881,-0.735098,0.942466,0.829306,-0.928573
체육도장,-0.997195,-0.994087,-0.982619,0.998617,-0.784841,-0.999791,1.000000,-0.139187,0.933761,0.748802,-0.949102,-0.817710,0.920793
축구장,0.064680,0.030834,0.320594,-0.086934,-0.504425,0.159399,-0.139187,1.000000,-0.484382,0.552119,-0.179800,0.683842,-0.514418
테니스장,-0.904355,-0.889376,-0.983969,0.913654,-0.511066,-0.940881,0.933761,-0.484382,1.000000,0.461990,-0.773508,-0.969563,0.999399
금상,-0.796309,-0.816345,-0.612751,0.782611,-0.998422,-0.735098,0.748802,0.552119,0.461990,1.000000,-0.919449,-0.230779,0.430967
은상,0.970014,0.977691,0.874137,-0.964348,0.940079,0.942466,-0.949102,-0.179800,-0.773508,-0.919449,1.000000,0.594785,-0.751072
동상,0.772334,0.750369,0.910354,-0.786317,0.285056,0.829306,-0.817710,0.683842,-0.969563,-0.230779,0.594785,1.000000,-0.977467
참가상,-0.889017,-0.872994,-0.977195,0.899013,-0.480962,-0.928573,0.920793,-0.514418,0.999399,0.430967,-0.751072,-0.977467,1.000000

In [76]:
import requests

url = 'http://www.kspo.or.kr/openapi/service/sportsNewFacilInfoService/getNewFacilInfoList'
params ={'serviceKey' : 'lr%2FMMSI2meh3E9iFzkQO5T69xq%2FJJj4Lx16t3sTDTeSZg%2BZOzr%2FECtqbZjg7WH1tBZYzuHOMczXal61YFVdRMA%3D%3D', 'pageNo' : '1', 'numOfRows' : '10', 'faciNm' : '365당구클럽', 'fcobNm' : '당구장업', 'ftypeNm' : '당구장', 'faciRoadAddr1' : '당구장', 'faciAddr1' : '강원도 .. 리 xx' }

response = requests.get(url, params=params)
print(response.content)

b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>99</resultCode><resultMsg>SERVICE KEY IS NOT REGISTERED ERROR.</resultMsg></header></response>'